### ISSUE TITLE
Create branch for conda only configuration. 

### ISSUE THREAD

**Issue by caspargross** [imgag/pathoLogic#20]
Some poeple might want to run the pipeline without docker or singularity. This branch should provide all options and installation instructions to run dependencies in conda environments only.

- [x] Adapt nextflow configs
- [x] Check run params in controller
- [x] Change install script
- [x] Update documentation

**Comment by Fohlen** [comment]
Can we close this @caspargross ?

**Comment by caspargross** [comment]
Fixed with issue 17121d185cb778752bb3945cd54e7ede2b981d2a on conda_env branch.
